# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker: 
      - image: cimg/node:20.3.0
    working_directory: ~/client

  # test:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    # docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/node
      # - image: cimg/node:current
      # - image: cimg/node:20.3.0

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/configuration-reference/?section=reference#save_cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: npm install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: npm run test

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test:
    jobs:
      - build

# ---------
# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:10.16

#     working_directory: ~/client

#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             - v1-dependencies-
#       - run: npm install
#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}
#       - run: npm test

#   deploy:
#     machine:
#       enabled: true

#     working_directory: ~/client

#     steps:
#       - add_ssh_keys:
#           fingerprints:
#             - "2b:62:fa:b9:e7:8c:34:0a:60:60:e0:56:ee:61:c4:d2"
#       - checkout
#       - run:
#           name: Push Master to Production
#           command: |
#             git push https://github.com/FarzanehSa/scheduler.git master:production

# workflows:
#   version: 2
#   test_and_deploy:
#     jobs:
#       - build:
#           filters:
#             branches:
#               ignore: production
#       - deploy:
#           filters:
#             branches:
#               ignore: production
#           requires:
#             - build